### PR TITLE
Add an additional word to instructions

### PR DESCRIPTION
**Pull request by diemella**
Added "please" to the instructions.

@gmmowry

### CODE REVIEW

**Comment by gmmowry** [comment]
Hi @diemella ! Please make sure you answer the questions before we merge this. You can check out the feature branch locally, answer the questions in the `git-definitions.md` file, go through the save-add-commit cycle, and when you push the branch up again, it will update this pull request. When you've got it completed, feel free to tag me again!

**Comment by diemella** [comment]
Hey @gmmowry! I created a two branches for this challenge. One to answer the questions and another I used to tag you. I've merged my answers branch to the remote base branch. Then, I've updated my local master. Should create another branch, make a small change, and submit PR to tag you?

**Comment by diemella** [comment]
@gmmowry ! I've updated this feature branch (tag-branch) to include the answers from the remote master. Then pushed this branch for a pull request. Thanks!

**Comment by gmmowry** [comment]
Ah gotcha! Thanks @diemella - looks great so :shipit:

**Pull request merged**
